name: "New Vocabulary Card"
description: "Add a word to generate a card"
title: "[Vocab] <word>"
labels: ["vocab", "generate"]
body:
  - type: input
    id: word
    attributes:
      label: Word
      description: Target English word
      placeholder: likeable
    validations:
      required: true
  - type: textarea
    id: meaning
    attributes:
      label: Meaning
      placeholder: Pleasant, friendly, and easy to like.
    validations:
      required: true
  - type: textarea
    id: example_sentence
    attributes:
      label: Example sentence
      placeholder: He is a genuinely likeable person with a great sense of humor.
    validations:
      required: true
